version: 2.1

jobs: 
  build:
    working_directory: ~/app
    docker:
      - image: arah24/docker-react
    steps:
      - checkout
      - run:
          name: "Executing docker run test"
          command: yarn && yarn test
      - setup_remote_docker: 
          version: 19.03.13

workflow:
  build:
    jobs:
      - test:
          context: 'react-counter'

