version: 2.1

jobs: 
  build:
    docker:
      - image: arah24/docker-react
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: "Executing docker run test"
          command: |
            echo $DOCKERHUB_USERNAME $DOCKERHUB_PASSWORD
            yarn test --coverage .
      - setup_remote_docker: 
          version: 19.03.13

workflow:
  build:
    jobs:
      - test:
          context: 'react-counter'

