version: 2.1

jobs: 
  test:
    docker:
      - image: arah24/docker-react-prod
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      run:
        name: "Executing docker run test"
        command: "docker run arah24/docker-react yarn test"

workflow:
  build_and_test:
    jobs:
      - test:
          context: 'react-counter'

